#' Creating wrong dates data
#'
#' This function takes the derived earliest positive lab collection date
#' generated by the system and derived and flags records where they are not
#' equal. Likewise, it takes the earliest symptom onset date generated by the
#' system and derived and flags records where they are not equal. We also add
#' the difference in days between the date. Finally, it filters to only include
#' records where the earliest symptom onset date or the earliest positive lab
#' collection date are wrong.
#'
#' @param clean_ccm_case_dates_data A tbl_df of CCM case dates data.
#' @param clean_ccm_case_lab_results_data A tbl_df of CCM case lab results
#' data.
#' @param clean_ccm_case_symptoms_data A tbl_df of CCM case symptoms data.
#'
#' @return A tbl_df of records with wrong dates.
#' @export
#'
#' @examples
#' `creating_wrong_dates_data(clean_ccm_case_dates_data, clean_ccm_case_lab_results_data, clean_ccm_case_symptoms_data)`
creating_wrong_dates_data <-
  function(clean_ccm_case_dates_data,
           clean_ccm_case_lab_results_data,
           clean_ccm_case_symptoms_data) {
    clean_ccm_case_dates_data %>%
      rename(
        episode_date_type_system = "episode_date_type",
        episode_date_system = "episode_date",
        reported_date_system = "reported_date"
      ) %>%
      # joining derived earliest symptom onset data
      left_join(
        deriving_earliest_symptom_onset_date(clean_ccm_case_symptoms_data),
        by = "investigation_number",
        suffix = c("_system", "_derived")
      ) %>%
      # joining derived earliest positive lab collection data
      left_join(
        deriving_earliest_positive_lab_collection_date(clean_ccm_case_lab_results_data),
        by = "investigation_number",
        suffix = c("_system", "_derived")
      ) %>%
      # joining derived earliest lab collection data
      left_join(
        deriving_earliest_lab_collection_date(clean_ccm_case_lab_results_data),
        by = "investigation_number",
        suffix = c("_system", "_derived")
      ) %>%
      # creating flags to indicate when the system generated and derived fields
      # differ
      mutate(
        is_earliest_symptom_onset_date_wrong = is_date_wrong(
          earliest_symptom_onset_date_system,
          earliest_symptom_onset_date_derived
        ),
        delta_earliest_symptom_onset_date_days = delta_dates_days(
          earliest_symptom_onset_date_system,
          earliest_symptom_onset_date_derived
        ),
        is_earliest_positive_lab_collection_date_wrong = is_date_wrong(
          earliest_positive_lab_collection_date_system,
          earliest_positive_lab_collection_date_derived
        ),
        delta_earliest_positive_lab_collection_date_days = delta_dates_days(
          earliest_positive_lab_collection_date_system,
          earliest_positive_lab_collection_date_derived
        ),
        is_earliest_lab_collection_date_wrong = is_date_wrong(
          earliest_lab_collection_date_system,
          earliest_lab_collection_date_derived
        ),
        delta_earliest_lab_collection_date_days = delta_dates_days(
          earliest_lab_collection_date_system,
          earliest_lab_collection_date_derived
        )
      ) %>%
      rowwise() %>%
      mutate(
        episode_date_derived = if_else(
          !episode_date_locked,
          deriving_ccm_episode_date(
            earliest_symptom_onset_date_derived,
            earliest_positive_lab_collection_date_derived,
            reported_date_system
          ),
          deriving_iphis_episode_date(
            earliest_symptom_onset_date_derived,
            earliest_positive_lab_collection_date_derived,
            reported_date_system
          )
        )
      ) %>%
      ungroup() %>%
      mutate(
        episode_date_type_derived = if_else(
          !episode_date_locked,
          deriving_ccm_episode_date_type(
            earliest_symptom_onset_date_derived,
            earliest_positive_lab_collection_date_derived,
            reported_date_system,
            episode_date_derived
          ),
          deriving_iphis_episode_date_type(
            earliest_symptom_onset_date_derived,
            earliest_positive_lab_collection_date_derived,
            reported_date_system
          )
        ),
        is_episode_date_type_wrong = episode_date_type_system != episode_date_type_derived,
        is_episode_date_wrong = is_date_wrong(episode_date_system, episode_date_derived),
        delta_episode_date_days = delta_dates_days(episode_date_system, episode_date_derived)
      ) %>%
      select(
        investigation_number,
        earliest_symptom_onset_date_system,
        earliest_symptom_onset_date_derived,
        is_earliest_symptom_onset_date_wrong,
        delta_earliest_symptom_onset_date_days,
        earliest_positive_lab_collection_date_system,
        earliest_positive_lab_collection_date_derived,
        is_earliest_positive_lab_collection_date_wrong,
        delta_earliest_positive_lab_collection_date_days,
        earliest_lab_collection_date_system,
        earliest_lab_collection_date_derived,
        is_earliest_lab_collection_date_wrong,
        delta_earliest_lab_collection_date_days,
        episode_date_type_system,
        episode_date_type_derived,
        is_episode_date_type_wrong,
        episode_date_system,
        episode_date_derived,
        is_episode_date_wrong,
        delta_episode_date_days
      ) %>%
      # we only want records where at least one of the fields is wrong
      filter(if_any(.cols = c(is_earliest_symptom_onset_date_wrong, is_earliest_positive_lab_collection_date_wrong, is_earliest_lab_collection_date_wrong, is_episode_date_type_wrong, is_episode_date_wrong)))
  }
