#' Reading CCM case symptoms data
#'
#' This function uses the read_csv() function from the readr package to read
#' the raw CCM case symptoms data in.
#'
#' @param ccm_case_symptoms_path A character representing the path to the raw
#' CCM case symptoms data.
#'
#' @return A tbl_df of raw CCM case symptoms data.
#' @export
#'
#' @examples
#' `reading_ccm_case_symptoms_data(here::here("data", "raw", "ccm_case_symptoms_data.csv"))`
reading_ccm_case_symptoms_data <- function(ccm_case_symptoms_path) {
  read_csv(
    file = ccm_case_symptoms_path,
    col_names = TRUE,
    col_types = cols(
      `Investigation Number` = col_character(),
      `Abdominal Pain` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Abdominal Pain Onset Date` = col_character(),
      `Abdominal Pain Recovery Date` = col_character(),
      `Acute functional decline` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Acute functional decline Onset Date` = col_character(),
      `Acute FD Recovery Date` = col_character(),
      `Acutely Altered Mental Status` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Acutely AM Onset Date` = col_character(),
      `Acutely AM Recovery Date` = col_character(),
      `Anorexia (Loss of Appetite)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Anorexia Onset Date` = col_character(),
      `Anorexia Recovery Date` = col_character(),
      `Joint Pain (Arthralgia)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Arthralgia Onset Date` = col_character(),
      `Arthralgia Recovery Date` = col_character(),
      `Chest Pain` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Chest Pain Onset Date` = col_character(),
      `Chest Pain Recovery Date` = col_character(),
      `Chills` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Chills Onset Date` = col_character(),
      `Chills Recovery Date` = col_character(),
      `Pink Eye (Conjunctivitis)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Pink Eye (Conjunctivitis) Onset Date` = col_character(),
      `Pink Eye (Conjunctivitis) Recovery Date` = col_character(),
      `Cough (New or worsening)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Cough (New or worsening) Onset Date` = col_character(),
      `Cough (New or worsening) Recovery Date` = col_character(),
      `Cough (Not new or worsening)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Cough Onset Date` = col_character(),
      `Cough Recovery Date` = col_character(),
      `Croup (Barking cough in children)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Croup Start Date` = col_character(),
      `Croup Recovery Date` = col_character(),
      `Decrease in blood pressure (Hypotension)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Hypotension Start Date` = col_character(),
      `Hypotension Recovery Date` = col_character(),
      `Decreased or Lack or Appetite` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Decreased or Lack or Appetite Onset Date` = col_character(),
      `Decreased or Lack Appetite Recovery Date` = col_character(),
      `Decrease or Loss of Smell or Taste` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Decrease of Smell or Taste Onset Date` = col_character(),
      `Decrease of Smell or Taste Recovery Date` = col_character(),
      `Diarrhea` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Diarrhea Onset Date` = col_character(),
      `Diarrhea Recovery Date` = col_character(),
      `Difficulty swallowing (Dysphagia)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Difficult Swallow Onset Date` = col_character(),
      `Difficult Swallow Recovery Date` = col_character(),
      `Dizziness` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Dizziness Onset Date` = col_character(),
      `Dizziness Recovery Date` = col_character(),
      `Ear ache` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Ear Ache Onset Date` = col_character(),
      `Ear Ache Recovery Date` = col_character(),
      `Falls` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Falls Onset Date` = col_character(),
      `Recovery Date Falls` = col_character(),
      `Fatigue lethargy or malaise` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Fatigue, lethargy or malaise Onset Date` = col_character(),
      `Fatigue lethargy or malaise Recovry Date` = col_character(),
      `Fever` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Fever Onset Date` = col_character(),
      `Fever Recovery Date` = col_character(),
      `Headache` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Headache Onset Date` = col_character(),
      `Headache Recovery Date` = col_character(),
      `Muscle Aches and Pain` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Muscle Aches and Pain Onset Date` = col_character(),
      `Muscle Aches and Pain Recovery Date` = col_character(),
      `Nasal Congestion` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Nasal Congestion Onset Date` = col_character(),
      `Nasal Congestion Recovery Date` = col_character(),
      `Nausea` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Nausea Onset Date` = col_character(),
      `Nausea Recovery Date` = col_character(),
      `Runny nose` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Runny Nose OnSet Date` = col_character(),
      `Runny Nose Recovery Date` = col_character(),
      `Shortness of Breath` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Shortness of Breath Onset Date` = col_character(),
      `Shortness of Breath Recovery Date` = col_character(),
      `Sore Throat` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Sore Throat Onset Date` = col_character(),
      `Recovery Date SoreThroat` = col_character(),
      `Vomiting` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Vomiting Onset Date` = col_character(),
      `Vomiting Recovery Date` = col_character(),
      `New or Worsening Chronic Conditions` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `New or Worsening Chronic Onset Date` = col_character(),
      `New or Worsening Chronic Recovery Date` = col_character(),
      `Tachycardia (Fast Heart Rate)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Tachycardia Onset Date` = col_character(),
      `Tachycardia Recovery Date` = col_character(),
      `Low blood pressure for age` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Low blood pressure Start Date` = col_character(),
      `Low blood pressure Recovery Date` = col_character(),
      `Hypoxia (unexplained)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Hypoxia (unexplained) Onset Date` = col_character(),
      `Hypoxia (unexplained) Recovery Date` = col_character(),
      `Difficulty feeding in infants` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Difficulty feeding in infants Onset Date` = col_character(),
      `Difficulty feeding infants Recovery Date` = col_character(),
      `Other<U+FFFD>Symptoms` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Other Symptom Onset Date` = col_character(),
      `Recovery Date Other Symp` = col_character(),
      `Fatigue` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Fatigue Onset Date` = col_character(),
      `Fatigue Recovery Date` = col_character(),
      `Fever (Not Recorded)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Fever (Not Recorded) Onset Date` = col_character(),
      `Hoarse Voice` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Hoarse Voice Onset Date` = col_character(),
      `Hoarse Voice Recovery Date` = col_character(),
      `Lethargy` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Lethargy Onset Date` = col_character(),
      `Lethargy Recovery Date` = col_character(),
      `Lymph Node Swelling/Pain(Lymphadenopath)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Node Swelling Onset Date` = col_character(),
      `Node Swelling Recovery Date` = col_character(),
      `Malaise (General Unwell Feeling)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Malaise Onset Date` = col_character(),
      `Malaise Recovery Date` = col_character(),
      `Myalgia (Muscle Pain)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Myalgia Onset Date` = col_character(),
      `Myalgia Recovery Date` = col_character(),
      `New olfactory or taste disorder` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `New OOTD Onset Date` = col_character(),
      `New OOTD Recovery Date` = col_character(),
      `Palpitations` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Palpitations Onset Date` = col_character(),
      `Palpitations Recovery Date` = col_character(),
      `Sneezing` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Sneezing Onset Date` = col_character(),
      `Sneezing Recovery Date` = col_character(),
      `Tachypnea (Rapid Breathing)` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Tachypnea Onset Date` = col_character(),
      `Tachypnea Recovery Date` = col_character(),
      `Delirium` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE),
      `Delirium Start Date` = col_character(),
      `Delirium Recovery Date` = col_character(),
      `Asymptomatic` = col_factor(levels = c("Yes", "No", "Unknown", "Not Reported"), include_na = TRUE)
    )
  )
}
